### ISSUE TITLE
Stylesheet contrast issues

### ISSUE THREAD

**Issue by endgame** [scrive/nix-workshop#1]
Some of the styling is quite low-contrast, which makes it harder to read and navigate than it could be:

* The `<h1>` of the currently-viewed page,
* I didn't notice the `<` and `>` previous/next page controls for a couple of minutes,
* Inline code (where syntax highlighting is not applied) is dark-on-dark.

**Comment by soareschen** [comment]
We are using the default theme provided by [mdBook](https://github.com/rust-lang/mdBook). Perhaps you can make suggestion there to improve the design. 

> Inline code (where syntax highlighting is not applied) is dark-on-dark.

The syntax highlighting CSS is configured in [theme/highlight.css](https://github.com/scrive/nix-workshop/blob/master/theme/highlight.css). Feel free to suggest a better color for inline code.

**Comment by endgame** [comment]
Didn't realise it was baked into the framework. Thanks for the pointer, re-reported upstream.
