### ISSUE TITLE
De-emphasise global packages?

### ISSUE THREAD

**Issue by endgame** [scrive/nix-workshop#3]
The first thing many Nix tutorials do is teach `nix-env -i` to install new packages. This is almost never what you want (set up shells instead). While it's convenient for new users, should it carry a warning saying that there are better ways, and you probably want to read ahead?

**Comment by soareschen** [comment]
The workshop targets both users who are interested in Nix, as well as users who are totally new or even slightly adverse to Nix. `nix-env -i` is a gateway drug for non-Nix users who are not familiar with Nix workflows. The first thing we can ask people to consider Nix is by telling them that Nix can be used as a drop-in replacement of Linux package managers. Hopefully after a few attempts of installing executables with `nix-env -i`, people can be more convinced of learning more about Nix.

Of course it would be good to improve the chapter to explain it more clearly. In particular we should phrase it in a way that can convince non-Nix users to give Nix a first try.
